---
title: "Mapping status Kanta lab"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params: 
  summary_data_5: NULL
editor_options: 
  chunk_output_type: console
---


```{r}
library(flexdashboard)
library(tidyverse)
```

```{r}
summary_data_5 <- params$summary_data_5
```


Column {.tabset}
-------------------------------------

### Mapping status summary

```{r}

toplot  <- summary_data_5 |>
  mutate(
    status = if_else(is.na(status), 'SUCCESFUL', status)
  ) |>
  group_by(status) |>
  summarise(n_codes = n(), n_subjects = sum(n_subjects), n_records = sum(n_records), .groups = 'drop') |>
  mutate(
    per_codes = n_codes / sum(n_codes) ,
    per_records = n_records / sum(n_records) 
  ) |>
  arrange(desc(per_records)) 

toplot |> 
  reactable::reactable(
    defaultPageSize = 20,
    columns = list(
      status = reactable::colDef(
        name = "Status",
        sortable = TRUE, 
        minWidth = 250
      ),
      n_codes = reactable::colDef(
        name = "Number of test+unit combinations",
        sortable = TRUE
      ),
      n_subjects = reactable::colDef(
        name = "Number of subjects",
        sortable = TRUE
      ),
      n_records = reactable::colDef(
        name = "Number of events",
        sortable = TRUE
      ),
      per_codes = reactable::colDef(
        name = "per_codes",
        format = reactable::colFormat(percent = TRUE, digits = 1)
      ),
      per_records = reactable::colDef(
        name = "per_records",
        format = reactable::colFormat(percent = TRUE, digits = 1)
      )
    ), 
    # rows color conditional on status, success is green, warning is yellow, error is red
    rowStyle = function(index) {
      if (toplot$status[[index]]  |> stringr::str_detect('SUCCESFUL')) {
        list(background = '#d8f8d8', color = 'black')
      } else if (toplot$status[[index]]  |> stringr::str_detect('WARNING')) {
        list(background = '#f8f8d8', color = 'black')
      } else if (toplot$status[[index]]  |> stringr::str_detect('ERROR')) {
        list(background = '#f8d8d8', color = 'black')
      } else if (toplot$status[[index]]  |> stringr::str_detect('IGNORED')) {
        list(background = '#d8d8d8', color = 'black')
      }
    }
  )


```   

### Mapping status per test+unit combination

```{r}

aaa   <- function(data) {
  if(length(data)<1) return(NA)
  if(length(data) == 1) return(NA)
  sparkline::sparkline(data, type = 'line', barColor = 'blue', barWidth = 5, barSpacing = 2, height = 20)
}

toplot  <- summary_data_5 |>
  # filter(measurement_concept_id == 3023602)  |>
  mutate(
    perplot= pmap(list(to_value_percentiles_tibble, group_value_min, group_value_max), ~{
      if (is.null(..1) | is.na(..2) | is.na(..3)) return(NA_real_)
      a <- ..1  |> distinct(value, .keep_all = T)
      if(nrow(a) < 2) return(NA_real_)
      #browser()
      new_percentiles_value <- seq(..2, ..3, length.out = 100)
      new_percentiles_points_a  <- approx(x = a$value, y = a$percentile, xout = new_percentiles_value, yleft = 0, yright = 1)$y
      new_percentiles_points_a
    })
  )  |> 
  #
  transmute(
    measurement_concept_id,
    concept_name,
    omop_quantity = omop_quantity,
    concept_code = paste0(TEST_NAME_ABBREVIATION, ' [', source_unit_clean, ']'),
    unit_fix = if_else(source_unit_clean == source_unit_clean_fix, '', paste0(source_unit_clean, ' -> ', source_unit_clean_fix)),
    n_subjects,
    n_records,
    p_NA_AA_A_LL_L_N_H_HH = paste0(p_NA_AA_A_LL_L_N_H_HH, '%'),
    value_percentiles = if_else(
      is.na(value_percentiles) | p_missing_values > 90, '',
      paste0(value_percentiles, " [", source_unit_valid, "]")
    ),
    to_value_percentiles = if_else(
      is.na(to_value_percentiles), '',
      paste0(to_value_percentiles, " [", to_source_unit_valid, "]")
    ),
    p_missing_values = if_else(
      is.na(p_missing_values), '',
      paste0('~', p_missing_values, '%')
    ),
    KS_test,
    perplot,
    status
  ) |>
  mutate(
    report_error = paste0(
      'https://github.com/FINNGEN/kanta_lab_harmonisation_public/issues/new?title= Auto repor for ', concept_code,
      '&body=Automatic report for ', concept_code, '
      ', 'status: ', status, '
      ', 'KS_test: ', KS_test, '
      ', 'value_percentiles: ', value_percentiles, '
      ', 'to_value_percentiles: ', to_value_percentiles, '
      Please describe the error here:'
    ) |> URLencode()
  ) |> 
  arrange(desc(n_records))


htmltools::browsable(
  htmltools::tagList(
    htmltools::tags$button(
      htmltools::tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = "Reactable.downloadDataCSV('cars-download-table', 'kanta_to_omop_mappings_status.csv')"
    ),
    
    toplot |> 
      reactable::reactable(
        filterable = TRUE,
        sortable = TRUE,
        searchable = TRUE,
        defaultPageSize = 15,
        showPageSizeOptions = TRUE,
        elementId = "cars-download-table",
        columns = list(
          measurement_concept_id = reactable::colDef(
            name = "ConceptId", 
            maxWidth = 100
          ),
          concept_name = reactable::colDef(
            name = "Omop Name"
          ),
          omop_quantity = reactable::colDef(
            name = "Omop Quantity", 
            maxWidth = 150
          ),
          concept_code = reactable::colDef(
            name = "TestCode [Unit]", 
            maxWidth = 150
          ),
          unit_fix = reactable::colDef(
            name = "Unit fix", 
            maxWidth = 150
          ),
          n_subjects = reactable::colDef(
            name = "Number of subjects", 
            maxWidth = 80
          ),
          n_records = reactable::colDef(
            name = "Number of events", 
            maxWidth = 80
          ),
          p_NA_AA_A_LL_L_N_H_HH = reactable::colDef(
            name = "[NA][AA, A, LL, L, N, H, HH]", 
            minWidth = 100
          ),
          value_percentiles = reactable::colDef(
            name = "Value percentiles", 
            minWidth = 150
          ),
          to_value_percentiles = reactable::colDef(
            name = "Harmonised value percentiles", 
            minWidth = 150
          ),
          p_missing_values = reactable::colDef(
            name = "Missing values %",
            maxWidth = 65
          ),
          KS_test = reactable::colDef(
            name = "KS test", 
            format = reactable::colFormat(digits = 2),
            maxWidth = 50
          ),
          perplot = reactable::colDef(
            name = "perplot",
            cell = aaa, 
            maxWidth = 150
          ), 
          status = reactable::colDef(
            name = "Status", 
            minWidth = 150
          ),
          report_error = reactable::colDef(
            name = "report_error",
            cell = function(value) {
              sprintf('<a href="%s" target="_blank">Report error</a>', value)
            },
            html = TRUE,
            maxWidth = 100
          )
        )
      )
  )
)

```


### Mapping status per OMOP conceptId

```{r}

# calculate the n_records_with_value
# group by measurement_concept_id and sum the n_records and   n_records_with_value
htmltools::browsable(
  htmltools::tagList(
    htmltools::tags$button(
      htmltools::tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = "Reactable.downloadDataCSV('cars-download-table2', 'kanta_omop_mappings_counts.csv')"
    ),
    
    summary_data_5 |> 
      filter(!is.na(measurement_concept_id)) |> filter(measurement_concept_id!=0)  |> 
      mutate(
        p_missing_values = if_else(is.na(p_missing_values), 100, p_missing_values),
        n_records_with_value = n_records * (1 - p_missing_values / 100) |> round()
      ) |>
      select(measurement_concept_id, concept_name, n_records, n_records_with_value, p_missing_values) |>
      group_by(measurement_concept_id, concept_name) |>
      summarise(
        n_records = sum(n_records),
        n_records_with_value = sum(n_records_with_value),
        n_codes = n(),
        .groups = 'drop'
      ) |>
      arrange(desc(n_records)) |>
      reactable::reactable(
        filterable = TRUE,
        sortable = TRUE,
        searchable = TRUE,
        defaultPageSize = 15,
        showPageSizeOptions = TRUE,
        elementId = "cars-download-table2",
        columns = list(
          measurement_concept_id = reactable::colDef(
            name = "ConceptId", 
            maxWidth = 100
          ),
          concept_name = reactable::colDef(
            name = "Omop Name"
          ),
          n_records_with_value = reactable::colDef(
            name = "Number of events with value", 
            maxWidth = 80
          ),
          n_records = reactable::colDef(
            name = "Number of events", 
            maxWidth = 80
          ),
          n_codes = reactable::colDef(
            name = "Number of test+unit combinations", 
            maxWidth = 80
          )
        )
      )
    
  )
)


```
